application.name=auth-service
application.version=@project.version@
logging.level.root=DEBUG
security.jwt.secret-key=fa1718f59a9d341be371ab2189bb02980c59755e7772a44f97a61c6043f628cb
security.jwt.expiration-time=360000
