application.name=auth-service
application.version=@project.version@
logging.level.root=DEBUG

# JWT , must be configured to be pulled as a secret from api gateway
security.jwt.secret-key=fa1718f59a9d341be371ab2189bb02980c59755e7772a44f97a61c6043f628cb
security.jwt.expiration-time=360000

# MailSender !!!! WARNING !! DO NOT COMMIT THIS TO PUBLIC REPO, MOVE TO SECRET PROPERTIES FILE
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.port=587
spring.mail.username=AKIAT2VGU64LGXR3E3T6
spring.mail.password=BF+qaL93kv3KdMv4cEOhTaRT1CaK05GLsaYw/6q+qw5u
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Host Address
server.host.address=http://localhost:8080
